import Head from "next/head";
import { TaskCreator } from "@/components/TaskCreator";
import { TaskList } from "@/components/TaskList";
import { Box, Container, Stack, useColorMode } from "@chakra-ui/react";
import { Menu } from "@/components/Menu";
import { motion, AnimatePresence, useIsPresent } from "framer-motion"

export default function Home() {
  const { colorMode } = useColorMode()

  const animations = {
    transition: { type: "spring", stiffness: 50, damping: 10 }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container pt='2' pb='4' minW='100%' height='100vh'>
        <Stack spacing='8' height='100%'>
          <Stack spacing='8' width='30%' margin='0 auto'>
            <Menu />
            <TaskCreator />
          </Stack>
          <TaskList />
        </Stack>
      </Container>
    </>
  );
}

export { getServerSideProps } from '@/chakra';
